#!/bin/bash

set -euo pipefail
source setup_svtools.sh
source $SVTOOLS_THIS_ROOT

CNVNATOR_PATH=$1
GENOTYPE_VCF=$2
COORDINATES_FILE=$3
SAMPLE=$4
#ALIGNMENT_BAM=$5
#SPLITTER_BAM=$6
COPYNUMBER_HIST=$7

svtools copynumber --cnvnator $CNVNATOR_PATH -s $SAMPLE -w 100 -r $COPYNUMBER_HIST -c $COORDINATES_FILE -v $GENOTYPE_VCF
